// lib/data.dart

const List<Map<String, dynamic>> destinations = [
  {"id": 1, "image": "assets/images/categories/mountain.png", "name": "Mountain"},
  {"id": 2, "image": "assets/images/categories/beach.png", "name": "Beach"},
  {"id": 3, "image": "assets/images/categories/national-park.png", "name": "National Park"},
  {"id": 4, "image": "assets/images/categories/historic-site.png", "name": "Historic Site"},
  {"id": 5, "image": "assets/images/categories/museum.png", "name": "Museum"},
  {"id": 6, "image": "assets/images/categories/art-gallery.png", "name": "Art Gallery"},
  {"id": 7, "image": "assets/images/categories/temple.png", "name": "Temple"},
  {"id": 8, "image": "assets/images/categories/church.png", "name": "Church"},
  {"id": 9, "image": "assets/images/categories/monument.png", "name": "Monument"},
  {"id": 10, "image": "assets/images/categories/archaeological-site.png", "name": "Archaeological Site"},
  {"id": 11, "image": "assets/images/categories/waterfall.png", "name": "Waterfall"},
  {"id": 12, "image": "assets/images/categories/lake.png", "name": "Lake"},
  {"id": 13, "image": "assets/images/categories/river.png", "name": "River"},
  {"id": 14, "image": "assets/images/categories/zoo.png", "name": "Zoo"},
  {"id": 15, "image": "assets/images/categories/botanical-garden.png", "name": "Botanical Garden"},
  {"id": 16, "image": "assets/images/categories/theme-park.png", "name": "Theme Park"},
  {"id": 17, "image": "assets/images/categories/wildlife-sanctuary.png", "name": "Wildlife Sanctuary"},
  {"id": 18, "image": "assets/images/categories/scenic-viewpoint.png", "name": "Scenic Viewpoint"},
  {"id": 19, "image": "assets/images/categories/village.png", "name": "Village"},
  {"id": 20, "image": "assets/images/categories/city.png", "name": "City"},
  {"id": 21, "image": "assets/images/categories/neighborhood.png", "name": "Neighborhood"},
  {"id": 22, "image": "assets/images/categories/market.png", "name": "Market"},
  {"id": 23, "image": "assets/images/categories/shopping-mall.png", "name": "Shopping Mall"},
  {"id": 24, "image": "assets/images/categories/library.png", "name": "Library"},
  {"id": 25, "image": "assets/images/categories/university.png", "name": "University"},
  {"id": 26, "image": "assets/images/categories/cave.png", "name": "Cave"},
  {"id": 27, "image": "assets/images/categories/fortress.png", "name": "Fortress"},
  {"id": 28, "image": "assets/images/categories/lighthouse.png", "name": "Lighthouse"},
  {"id": 29, "image": "assets/images/categories/aquarium.png", "name": "Aquarium"},
  {"id": 30, "image": "assets/images/categories/cultural-landmark.png", "name": "Cultural Landmark"},
  {"id": 31, "image": "assets/images/categories/rock.png", "name": "Rock"},
  {"id": 32, "image": "assets/images/categories/coral-reef.png", "name": "Coral Reef"},
  {"id": 33, "image": "assets/images/categories/tea-plantation.png", "name": "Tea Plantation"},
  {"id": 34, "image": "assets/images/categories/forest.png", "name": "Forest"},
];

const List<Map<String, dynamic>> activities = [
  {"id": 1, "image": "assets/images/activities/hiking.png", "name": "Hiking"},
  {"id": 2, "image": "assets/images/activities/surfing.png", "name": "Surfing"},
  {"id": 3, "image": "assets/images/activities/scuba-diving.png", "name": "Scuba Diving"},
  {"id": 4, "image": "assets/images/activities/wildlife-safari.png", "name": "Wildlife Safari"},
  {"id": 5, "image": "assets/images/activities/bird-watching.png", "name": "Bird Watching"},
  {"id": 6, "image": "assets/images/activities/cultural-tours.png", "name": "Cultural Tours"},
  {"id": 7, "image": "assets/images/activities/historical-tours.png", "name": "Historical Tours"},
  {"id": 8, "image": "assets/images/activities/temple-visits.png", "name": "Temple Visits"},
  {"id": 9, "image": "assets/images/activities/waterfall-visits.png", "name": "Waterfall Visits"},
  {"id": 10, "image": "assets/images/activities/whale-watching.png", "name": "Whale Watching"},
  {"id": 11, "image": "assets/images/activities/fishing.png", "name": "Fishing"},
  {"id": 12, "image": "assets/images/activities/camping.png", "name": "Camping"},
  {"id": 13, "image": "assets/images/activities/rock-climbing.png", "name": "Rock Climbing"},
  {"id": 14, "image": "assets/images/activities/cycling.png", "name": "Cycling"},
  {"id": 15, "image": "assets/images/activities/kayaking.png", "name": "Kayaking"},
  {"id": 16, "image": "assets/images/activities/canoeing.png", "name": "Canoeing"},
  {"id": 17, "image": "assets/images/activities/boating.png", "name": "Boating"},
  {"id": 18, "image": "assets/images/activities/hot-air-ballooning.png", "name": "Hot Air Ballooning"},
  {"id": 19, "image": "assets/images/activities/tea-plantation-tours.png", "name": "Tea Plantation Tours"},
  {"id": 20, "image": "assets/images/activities/elephant-rides.png", "name": "Elephant Rides"},
  {"id": 21, "image": "assets/images/activities/village-tours.png", "name": "Village Tours"},
  {"id": 22, "image": "assets/images/activities/food-tours.png", "name": "Food Tours"},
  {"id": 23, "image": "assets/images/activities/trekking.png", "name": "Trekking"},
  {"id": 24, "image": "assets/images/activities/photography.png", "name": "Photography"},
  {"id": 25, "image": "assets/images/activities/caving.png", "name": "Caving"},
];
